// This file is typically generated by the Supabase CLI, but we define a minimal structure here.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          first_name: string | null
          last_name: string | null
          avatar_url: string | null
          updated_at: string | null
          phone: string | null
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Row']>
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      restaurants: {
        Row: {
          id: string
          user_id: string | null
          name: string
          description: string | null
          image_url: string | null
          cover_image_url: string | null
          plan: 'free' | 'basic' | 'premium' | 'premium_gift'
          phone: string | null
          email: string | null
          cnpj: string | null
          category: string | null
          whatsapp_url: string | null
          ifood_url: string | null
          other_url: string | null
          address: string | null
          number: string | null
          neighborhood: string | null
          city: string | null
          state: string | null
          cep: string | null
          latitude: number | null
          longitude: number | null
          opening_hours: Json | null
          created_at: string
          external_url: string | null
        }
        Insert: Omit<Database['public']['Tables']['restaurants']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['restaurants']['Row']>
        Relationships: [
          {
            foreignKeyName: "restaurants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_favorites: {
        Row: {
          id: string
          user_id: string
          restaurant_id: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['user_favorites']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['user_favorites']['Row']>
        Relationships: [
          {
            foreignKeyName: "user_favorites_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      menu_categories: {
        Row: {
          id: string
          restaurant_id: string
          name: string
          order_index: number | null
          is_active: boolean | null
          created_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['menu_categories']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['menu_categories']['Row']>
        Relationships: [
          {
            foreignKeyName: "menu_categories_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      menu_items: {
        Row: {
          id: string
          category_id: string
          name: string
          description: string | null
          price: number
          image_url: string | null
          order_index: number | null
          is_active: boolean | null
          created_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['menu_items']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['menu_items']['Row']>
        Relationships: [
          {
            foreignKeyName: "menu_items_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "menu_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      restaurant_gallery: {
        Row: {
          id: string
          restaurant_id: string
          image_url: string
          caption: string | null
          order_index: number | null
          created_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['restaurant_gallery']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['restaurant_gallery']['Row']>
        Relationships: [
          {
            foreignKeyName: "restaurant_gallery_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      restaurant_plan: 'free' | 'basic' | 'premium' | 'premium_gift'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Exportando tipos derivados para uso fácil
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Restaurant = Database['public']['Tables']['restaurants']['Row'];
export type MenuCategory = Database['public']['Tables']['menu_categories']['Row'];
export type MenuItem = Database['public']['Tables']['menu_items']['Row'];
export type GalleryImage = Database['public']['Tables']['restaurant_gallery']['Row'];
export type RestaurantPlan = Database['public']['Enums']['restaurant_plan'];

// Tipos compostos
export type MenuCategoryWithItems = MenuCategory & {
  menu_items: MenuItem[];
};

// Tipo para resultados de busca de restaurantes (inclui distance_km)
export type RestaurantWithDistance = Restaurant & {
  distance_km: number | null;
};

// Tipo para favoritos (que inclui dados do restaurante)
export type FavoriteRestaurant = {
  restaurant: Restaurant;
};