export const restaurantCategories = [
  { value: 'acai', label: 'Açaí' },
  { value: 'arabe', label: 'Árabe' },
  { value: 'brasileira', label: 'Brasileira' },
  { value: 'cafeteria', label: 'Cafeteria' },
  { value: 'chinesa', label: 'Chinesa' },
  { value: 'churrasco', label: 'Churrasco' },
  { value: 'doces-bolos', label: 'Doces e Bolos' },
  { value: 'francesa', label: 'Francesa' },
  { value: 'frutos-do-mar', label: 'Frutos do Mar' },
  { value: 'hamburgueria', label: 'Hamburgueria' },
  { value: 'indiana', label: 'Indiana' },
  { value: 'italiana', label: 'Italiana' },
  { value: 'japonesa', label: 'Japonesa' },
  { value: 'mexicana', label: 'Mexicana' },
  { value: 'padaria', label: 'Padaria' },
  { value: 'pizzaria', label: 'Pizzaria' },
  { value: 'sanduiches', label: 'Sanduíches' },
  { value: 'saudavel', label: 'Saudável' },
  { value: 'sorveteria', label: 'Sorveteria' },
  { value: 'tailandesa', label: 'Tailandesa' },
  { value: 'vegana', label: 'Vegana' },
  { value: 'vegetariana', label: 'Vegetariana' },
  { value: 'outros', label: 'Outros' },
];